ignore_ttl: 168h # 7 days, each entry must be revalidated after this time, and either removed or renewed (with a new date)

ignore:
  - id: GO-2025-3521
    reason: No fix available, code not reachable in production.
    date: 2026-09-16
  - id: GO-2025-3547
    reason: No fix available, kube-apiserver race not reachable in production.
    date: 2026-09-16
